baseURL = 'https://open-filament.github.io/'
languageCode = 'en-us'
title = 'Open-Filament'
theme = 'open-filaments-theme'
sectionPagesMenu = "main"

[params]
logo = "/logo.png"
respository = "https://github.com/open-filament/open-filament.github.io"